# Generated by Django 5.2.7 on 2025-10-02 14:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Data/hora de criação"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Data/hora da última atualização"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete: False = deletado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("matched", "Matched pelo Admin"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status da candidatura",
                        max_length=20,
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        blank=True, help_text="Data/hora do match pelo admin", null=True
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, help_text="Notas internas do admin")),
            ],
            options={
                "verbose_name": "Candidatura",
                "verbose_name_plural": "Candidaturas",
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
