# Generated by Django 5.2.7 on 2025-10-02 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("candidates", "0001_initial"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                help_text="Candidato que se candidatou",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                help_text="Vaga para a qual se candidatou",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="matched_by_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin que fez o match (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "-created_at"], name="application_status_2bb59d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["job", "status"], name="application_job_id_606b4d_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate", "-created_at"], name="application_candida_55baf4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "candidate")},
        ),
    ]
