version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: talentbase_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: talentbase_dev
      POSTGRES_USER: talentbase
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talentbase"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: talentbase_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
