version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: talentbase_postgres_prod_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: talentbase_prod_test
      POSTGRES_USER: talentbase_admin
      POSTGRES_PASSWORD: test_password_123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talentbase_admin -d talentbase_prod_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - talentbase_prod_test

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: talentbase_redis_prod_test
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - talentbase_prod_test

  # Django Backend API (Production Image)
  api:
    image: talentbase-api:test
    container_name: talentbase_api_prod_test
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=talentbase.settings.development
      - DB_NAME=talentbase_prod_test
      - DB_USER=talentbase_admin
      - DB_PASSWORD=test_password_123
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=test-secret-key-for-production-testing-only-do-not-use-in-real-prod
      - ALLOWED_HOSTS=localhost,127.0.0.1,api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - talentbase_prod_test

  # Remix Frontend (Production Image)
  web:
    image: talentbase-web:test
    container_name: talentbase_web_prod_test
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=test-session-secret-for-production-testing-only
      - PORT=3000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - talentbase_prod_test

networks:
  talentbase_prod_test:
    driver: bridge
