# Generated by Django 5.2.7 on 2025-10-02 14:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Data/hora de criação"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Data/hora da última atualização"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete: False = deletado"
                    ),
                ),
                ("title", models.CharField(help_text="Título da vaga", max_length=200)),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("SDR/BDR", "SDR/BDR"),
                            ("AE/Closer", "Account Executive/Closer"),
                            ("CSM", "Customer Success Manager"),
                        ],
                        db_index=True,
                        help_text="Tipo de posição",
                        max_length=50,
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        choices=[("junior", "Júnior"), ("pleno", "Pleno"), ("senior", "Sênior")],
                        help_text="Nível de senioridade",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Descrição completa da vaga")),
                ("responsibilities", models.TextField(help_text="Responsabilidades do cargo")),
                (
                    "required_skills",
                    models.JSONField(
                        default=list,
                        help_text="Habilidades requeridas (ex: ['Outbound', 'HubSpot'])",
                    ),
                ),
                (
                    "required_tools",
                    models.JSONField(
                        default=list, help_text="Ferramentas requeridas (ex: ['Salesforce'])"
                    ),
                ),
                (
                    "sales_cycle",
                    models.CharField(
                        blank=True, help_text="Ciclo de vendas da empresa", max_length=100
                    ),
                ),
                (
                    "avg_ticket",
                    models.CharField(
                        blank=True, help_text="Ticket médio da empresa", max_length=100
                    ),
                ),
                ("location", models.CharField(help_text="Localização da vaga", max_length=100)),
                ("is_remote", models.BooleanField(default=False, help_text="Trabalho remoto?")),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, help_text="Faixa salarial (ex: R$ 5k-8k)", max_length=100
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa que publicou a vaga",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga de Emprego",
                "verbose_name_plural": "Vagas de Emprego",
                "db_table": "job_postings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["position_type", "is_active"], name="job_posting_positio_33ad0f_idx"
                    ),
                    models.Index(
                        fields=["company", "-created_at"], name="job_posting_company_93093a_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"], name="job_posting_is_acti_358443_idx"
                    ),
                ],
            },
        ),
    ]
