# Generated by Django 5.2.7 on 2025-10-02 14:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Data/hora de criação"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Data/hora da última atualização"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete: False = deletado"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, help_text="Score de 0.00 a 100.00", max_digits=5
                    ),
                ),
                (
                    "rank_position",
                    models.PositiveIntegerField(
                        blank=True, help_text="Posição geral no ranking (opcional)", null=True
                    ),
                ),
                (
                    "ranking_notes",
                    models.TextField(
                        blank=True, help_text="Notas sobre o ranking (critérios, justificativa)"
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        help_text="Candidato sendo ranqueado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to="candidates.candidateprofile",
                    ),
                ),
                (
                    "ranked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que atribuiu o ranking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking de Candidato",
                "verbose_name_plural": "Rankings de Candidatos",
                "db_table": "rankings",
                "ordering": ["-score", "rank_position"],
                "indexes": [
                    models.Index(fields=["-score"], name="rankings_score_4b0812_idx"),
                    models.Index(fields=["rank_position"], name="rankings_rank_po_3f4d9e_idx"),
                ],
            },
        ),
    ]
