# Generated by Django 5.2.7 on 2025-10-08 18:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatusAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("old_status", models.BooleanField(help_text="Previous is_active value")),
                ("new_status", models.BooleanField(help_text="New is_active value")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("activate", "Activate"),
                            ("deactivate", "Deactivate"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", help_text="Reason for status change"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="Admin who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose status was changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Status Audit",
                "verbose_name_plural": "User Status Audits",
                "db_table": "user_status_audits",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="user_status_timesta_6836cb_idx"),
                    models.Index(
                        fields=["user", "-timestamp"], name="user_status_user_id_b057d8_idx"
                    ),
                ],
            },
        ),
    ]
