# Generated by Django 5.2.7 on 2025-10-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_add_user_status_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_required",
            field=models.BooleanField(
                default=False, help_text="Usuário precisa redefinir senha no próximo login?"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.UUIDField(
                blank=True, help_text="Token único para redefinir senha", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_expires",
            field=models.DateTimeField(
                blank=True, help_text="Data de expiração do token de redefinição", null=True
            ),
        ),
    ]
