# Generated by Django 5.2.7 on 2025-10-02 14:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Data/hora de criação"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Data/hora da última atualização"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete: False = deletado"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(help_text="Razão social ou nome fantasia", max_length=200),
                ),
                ("cnpj", models.CharField(help_text="CNPJ (será encriptado)", max_length=255)),
                ("website", models.URLField(help_text="Site da empresa")),
                (
                    "industry",
                    models.CharField(
                        help_text="Setor/indústria (ex: SaaS, Fintech)", max_length=100
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 funcionários"),
                            ("11-50", "11-50 funcionários"),
                            ("51-200", "51-200 funcionários"),
                            ("201+", "Mais de 200 funcionários"),
                        ],
                        help_text="Tamanho da empresa",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Descrição da empresa")),
                (
                    "contact_person_name",
                    models.CharField(help_text="Nome do responsável", max_length=200),
                ),
                (
                    "contact_person_email",
                    models.EmailField(help_text="Email do responsável", max_length=254),
                ),
                (
                    "contact_person_phone",
                    models.CharField(help_text="Telefone do responsável", max_length=20),
                ),
                (
                    "created_by_admin",
                    models.BooleanField(
                        default=False,
                        help_text="True se criado por admin, False se self-registered",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Usuário associado (null se criado por admin)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Empresa",
                "verbose_name_plural": "Perfis de Empresas",
                "db_table": "company_profiles",
                "indexes": [
                    models.Index(fields=["industry"], name="company_pro_industr_dbd29a_idx"),
                    models.Index(fields=["-created_at"], name="company_pro_created_cd277b_idx"),
                ],
            },
        ),
    ]
