# Generated by Django 5.2.7 on 2025-10-03 16:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="cnpj",
            field=encrypted_model_fields.fields.EncryptedCharField(
                help_text="CNPJ encriptado (PII protection)"
            ),
        ),
    ]
