# Generated by Django 5.2.7 on 2025-10-09 03:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Data/hora de criação"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Data/hora da última atualização"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete: False = deletado"
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(
                        db_index=True, help_text="Recipient email address", max_length=255
                    ),
                ),
                ("subject", models.CharField(help_text="Email subject line", max_length=200)),
                (
                    "template_name",
                    models.CharField(db_index=True, help_text="Template name used", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Email sending status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if sending failed"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when email was sent", null=True
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_index=True, help_text="Celery task ID", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"], name="core_emaill_created_bf3f08_idx"
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"], name="core_emaill_recipie_4a18db_idx"
                    ),
                    models.Index(
                        fields=["template_name", "-created_at"],
                        name="core_emaill_templat_89922e_idx",
                    ),
                ],
            },
        ),
    ]
