# Generated by Django 5.2.7 on 2025-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_add_email_log_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Celery task ID (null in EAGER mode)",
                max_length=100,
                null=True,
            ),
        ),
    ]
