description = "Executes the Adv Elicit task from the BMad Method."
prompt = """
Execute the following BMad Method task workflow:

@../talentbase-v1/bmad/core/tasks/adv-elicit.md

Follow all instructions and complete the task as defined.
"""
