description = "Executes the Retrospective task from the BMad Method."
prompt = """
Execute the following BMad Method task workflow:

@../talentbase-v1/bmad/bmm/tasks/retrospective.md

Follow all instructions and complete the task as defined.
"""
