description = "Executes the Workflow task from the BMad Method."
prompt = """
Execute the following BMad Method task workflow:

@../talentbase-v1/bmad/core/tasks/workflow.md

Follow all instructions and complete the task as defined.
"""
