# Generated by Django 5.2.7 on 2025-10-09 22:30

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_make_fields_optional_for_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="city",
            field=models.CharField(
                blank=True, default="", help_text="Cidade do candidato", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="pitch_video_type",
            field=models.CharField(
                blank=True,
                choices=[("s3", "S3 Upload"), ("youtube", "YouTube")],
                default="",
                help_text="Tipo de vídeo: upload direto (S3) ou YouTube",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="pitch_video_url",
            field=models.URLField(blank=True, help_text="URL do vídeo pitch (S3 ou YouTube)"),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="profile_photo_url",
            field=models.URLField(blank=True, help_text="URL da foto de perfil (S3)", null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL do vídeo de apresentação no YouTube (DEPRECATED - use pitch_video_url)",
                validators=[candidates.models.validate_youtube_url],
            ),
        ),
    ]
