# Generated by Django 5.2.7 on 2025-10-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_add_profile_photo_and_pitch_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="accepts_pj",
            field=models.BooleanField(
                default=False, help_text="Aceita trabalhar como PJ", verbose_name="Aceita PJ"
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_summary",
            field=models.JSONField(
                default=dict,
                help_text='\n        Resumo estruturado de experiências:\n        {\n          "sdr": {\n            "has_experience": false,\n            "details": []\n          },\n          "sales": {\n            "outbound_years": 10,\n            "inbound_years": 10,\n            "inside_sales_years": 10,\n            "field_sales_years": 3,\n            "arr_range": "60K-120K ARR",\n            "sales_cycle": "1-3 meses"\n          },\n          "csm": {\n            "retention_years": 10,\n            "expansion_years": 10\n          }\n        }\n        ',
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="languages",
            field=models.JSONField(
                default=list,
                help_text="Lista de idiomas: [{'name': 'Português', 'level': 'Nativo'}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="pcd",
            field=models.BooleanField(
                default=False, help_text="Indica se é PCD", verbose_name="Pessoa com Deficiência"
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="position_interest",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Posição de interesse (ex: 'Account Manager/CSM', 'SDR', 'AE')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="public_sharing_enabled",
            field=models.BooleanField(default=False, help_text="Compartilhamento público ativado?"),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="relocation",
            field=models.BooleanField(
                default=False,
                help_text="Disponível para relocação",
                verbose_name="Disponível para mudança",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="share_link_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="Data/hora da geração do link de compartilhamento", null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="travel_availability",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Disponibilidade para viagens (ex: 'Sim, semanalmente', 'Sim, eventualmente', 'Não')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="work_model",
            field=models.CharField(
                choices=[("remote", "Remoto"), ("hybrid", "Híbrido"), ("onsite", "Presencial")],
                default="hybrid",
                help_text="Modelo de trabalho preferido",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="company_logo_url",
            field=models.URLField(blank=True, help_text="URL do logo da empresa (S3)", null=True),
        ),
    ]
