# Generated by Django 5.2.7 on 2025-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_add_story_3_2_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="academic_degree",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Formação acadêmica (ex: 'Ensino Superior Completo', 'MBA')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="active_prospecting_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiência em prospecção ativa (ex: 'Entre 3 e 5 anos')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="contract_signed",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o contrato foi assinado",
                verbose_name="Contrato Assinado",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="field_sales_experience",
            field=models.CharField(
                blank=True, default="", help_text="Experiência em field sales", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="has_drivers_license",
            field=models.BooleanField(
                default=False, help_text="Possui carteira de motorista", verbose_name="Possui CNH"
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="has_vehicle",
            field=models.BooleanField(
                default=False,
                help_text="Possui veículo próprio",
                verbose_name="Possui veículo próprio",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="inbound_qualification_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiência em qualificação de leads inbound",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="inbound_sales_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiência em vendas para leads inbound",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="inside_sales_experience",
            field=models.CharField(
                blank=True, default="", help_text="Experiência em inside sales", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="interview_date",
            field=models.DateField(blank=True, help_text="Data da entrevista", null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="is_pcd",
            field=models.BooleanField(
                default=False,
                help_text="Pessoa com Deficiência (campo alternativo para compatibilidade CSV)",
                verbose_name="PCD",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="minimum_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Remuneração mínima mensal desejada (R$)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="outbound_sales_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiência em vendas para leads outbound",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="portfolio_expansion_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiência em expansão/venda para carteira",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="portfolio_retention_experience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiência em retenção de carteira de clientes",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="portfolio_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tamanho da carteira gerida (ex: 'Entre 10 e 30 contas')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="positions_of_interest",
            field=models.JSONField(
                default=list, help_text="Lista de posições de interesse (ex: ['SDR', 'AE', 'CSM'])"
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="relocation_availability",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Disponibilidade para mudança (ex: 'Sim', 'Não', 'Depende da oportunidade')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="salary_notes",
            field=models.TextField(
                blank=True, default="", help_text="Observações sobre remuneração"
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="zip_code",
            field=models.CharField(blank=True, default="", help_text="CEP", max_length=10),
        ),
    ]
