name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback (dev/prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Rollback ECS Services
        run: |
          CLUSTER="talentbase-${{ inputs.environment }}"
          aws ecs update-service --cluster $CLUSTER --service talentbase-api-${{ inputs.environment }} --force-new-deployment
          aws ecs update-service --cluster $CLUSTER --service talentbase-web-${{ inputs.environment }} --force-new-deployment
